services:
  proxy:
    build: .
    ports:
      - "8080:80"
    environment:
      ENABLE_HTTPS: "false"
      ROUTE_MAP: >
        {
          "/mock/v1": "http://upstream:8080/v1"
        }
    depends_on:
      - upstream

  upstream:
    image: mendhak/http-https-echo:35
    environment:
      HTTP_PORT: "8080"
